version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: postiz-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postiz
      POSTGRES_PASSWORD: postizpwd
      POSTGRES_DB: postizdb
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: postiz-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postiz:postizpwd@postgres:5432/postizdb
      # Diğer backend environment variable'larınızı buraya ekleyin
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: postiz-frontend
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=production
      # Railway'de bu değişkeni Railway dashboard'dan backend'inizin public URL'siyle ayarlayın
      - NEXT_PUBLIC_BACKEND_URL=http://postiz-backend:3000
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres-data:
