[services.backend]
  source = "apps/backend"
  start = "pnpm --filter backend start"
  build = "pnpm --filter backend build"

[services.frontend]
  source = "apps/frontend"
  start = "pnpm --filter frontend start"
  build = "pnpm install --frozen-lockfile && pnpm --filter frontend build"

[services.cron]
  source = "apps/cron"
  start = "pnpm --filter cron start"
  build = "pnpm --filter cron build"

[services.commands]
  source = "apps/commands"
  start = "pnpm --filter command start"
  build = "pnpm --filter command build"

[services.workers]
  source = "apps/workers"
  start = "pnpm --filter workers start"
  build = "pnpm --filter workers build"